### ISSUE TITLE
[Bug] Player online count not updating

### ISSUE THREAD

**Issue by Pantera07** [Elytrium/FastMOTD#14]
https://github.com/Elytrium/FastMOTD/commit/4c0c015fef5e45e034f5f88b8d69c7b3984d61e6
Happened after this update

```
[12:57:10] [Velocity Task Scheduler - #76/ERROR]: Exception in task net.elytrium.fastmotd.FastMOTD$$Lambda$1166/0x00000001007bbc10@37e1b46d by plugin FastMOTD
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) ~[?:?]
	at java.util.LinkedList$ListItr.next(LinkedList.java:892) ~[?:?]
	at net.elytrium.fastmotd.utils.ByteBufCopyThreadLocal.release(ByteBufCopyThreadLocal.java:42) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.localReplaceOnline(MOTDBytesHolder.java:132) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.replaceOnline(MOTDBytesHolder.java:116) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDHolder.replaceOnline(MOTDHolder.java:46) ~[?:?]
	at net.elytrium.fastmotd.utils.MOTDGenerator.update(MOTDGenerator.java:120) ~[?:?]
	at net.elytrium.fastmotd.FastMOTD.updateMOTD(FastMOTD.java:286) ~[?:?]
	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-57ca66de-b181)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:57:13] [Velocity Task Scheduler - #76/ERROR]: Exception in task net.elytrium.fastmotd.FastMOTD$$Lambda$1166/0x00000001007bbc10@37e1b46d by plugin FastMOTD
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-57ca66de-b181)]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-57ca66de-b181)]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-57ca66de-b181)]
	at net.elytrium.fastmotd.utils.ByteBufCopyThreadLocal.release(ByteBufCopyThreadLocal.java:43) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.localReplaceOnline(MOTDBytesHolder.java:132) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.replaceOnline(MOTDBytesHolder.java:116) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDHolder.replaceOnline(MOTDHolder.java:46) ~[?:?]
	at net.elytrium.fastmotd.utils.MOTDGenerator.update(MOTDGenerator.java:120) ~[?:?]
	at net.elytrium.fastmotd.FastMOTD.updateMOTD(FastMOTD.java:286) ~[?:?]
	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-57ca66de-b181)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

https://mclo.gs/589Vm39

**Comment by Pantera07** [comment]
https://github.com/Elytrium/FastMOTD/commit/1e8badc33717a70974072805b974bbb399caabd5
This build also has this bug.

```
[10:12:09] [Velocity Task Scheduler - #8/ERROR]: Exception in task net.elytrium.fastmotd.FastMOTD$$Lambda$1175/0x0000000100809168@4672bd3c by plugin FastMOTD
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) ~[?:?]
	at java.util.LinkedList$ListItr.next(LinkedList.java:892) ~[?:?]
	at net.elytrium.fastmotd.utils.ByteBufCopyThreadLocal.release(ByteBufCopyThreadLocal.java:42) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.localReplaceOnline(MOTDBytesHolder.java:109) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDBytesHolder.replaceOnline(MOTDBytesHolder.java:98) ~[?:?]
	at net.elytrium.fastmotd.holder.MOTDHolder.replaceOnline(MOTDHolder.java:45) ~[?:?]
	at net.elytrium.fastmotd.utils.MOTDGenerator.update(MOTDGenerator.java:119) ~[?:?]
	at net.elytrium.fastmotd.FastMOTD.updateMOTD(FastMOTD.java:279) ~[?:?]
	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

https://mclo.gs/3YhpzzS

**Comment by hevav** [comment]
I'm really sorry it took me so long to check this bug.
I've been very busy (I even shut down my Minecraft server for a while).
