### ISSUE TITLE
[bug] Using 'null' causes a bug

### ISSUE THREAD

**Issue by Pantera07** [Elytrium/FastMOTD#15]
https://github.com/Elytrium/FastMOTD/commit/146b089a113b824e85be3e41531533ce1e574435
Happened after this update

ex)
```
descriptions: null
favicons: null
information: null
```

```
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.toYamlString(YamlConfig.java:578)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.toYamlString(YamlConfig.java:530)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.writeConfigKeyValue(YamlConfig.java:362)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.writeConfigKeyValue(YamlConfig.java:358)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.writeConfigKeyValue(YamlConfig.java:358)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.save(YamlConfig.java:302)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.java.commons.config.YamlConfig.reload(YamlConfig.java:80)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:143)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.fastmotd.FastMOTD.onProxyInitialization(FastMOTD.java:139)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at net.elytrium.fastmotd.Lmbda$11.execute(Unknown Source)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:17:46] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:17:47] [Velocity Async Event Executor - #0/WARN]: Failed to load favicon second-server-icon.png. Ensure that the file exists or modify config.yml
[01:17:47] [Velocity Async Event Executor - #0/WARN]: Failed to load favicon second-server-icon.png. Ensure that the file exists or modify config.yml
[01:17:47] [Velocity Async Event Executor - #0/WARN]: Failed to load favicon second-server-icon.png. Ensure that the file exists or modify config.yml
```

**Comment by luucfr** [comment]
Solution ?

**Comment by XakVit1122** [comment]
up
