### ISSUE TITLE
new dev version erro:

### ISSUE THREAD

**Issue by thiagogebrimm** [Elytrium/FastMOTD#16]
```
[20:06:19 ERROR]: Exception in task net.elytrium.fastmotd.FastMOTD$$Lambda$1175/0x0000000801780f58@7414bf05 by plugin FastMOTD
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[velocity.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147) ~[velocity.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[velocity.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at net.elytrium.fastmotd.utils.ByteBufCopyThreadLocal.release(ByteBufCopyThreadLocal.java:43) ~[?:?]
        at net.elytrium.fastmotd.holder.MOTDBytesHolder.localReplaceOnline(MOTDBytesHolder.java:132) ~[?:?]
        at net.elytrium.fastmotd.holder.MOTDBytesHolder.replaceOnline(MOTDBytesHolder.java:116) ~[?:?]
        at net.elytrium.fastmotd.holder.MOTDHolder.replaceOnline(MOTDHolder.java:46) ~[?:?]
        at net.elytrium.fastmotd.utils.MOTDGenerator.update(MOTDGenerator.java:120) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.updateMOTD(FastMOTD.java:286) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228) ~[velocity.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Pantera07** [comment]
https://github.com/Elytrium/FastMOTD/issues/14
