### ISSUE TITLE
Error while pinging server: `NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'`

### ISSUE THREAD

**Issue by ChefMC** [Elytrium/FastMOTD#25]
Error while pinging server (Velocity):

```
[01:05:04] [Application-Thread/INFO] [com.velocitypowered.proxy.Velocity]: Done (11,89s)!
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.lang.reflect.InvocationTargetException
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.viaversion.viaversion.velocity.handlers.VelocityChannelInitializer.initChannel(VelocityChannelInitializer.java:57)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[01:05:04] [Netty NIO Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 35 more
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.lang.reflect.InvocationTargetException
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.viaversion.viaversion.velocity.handlers.VelocityChannelInitializer.initChannel(VelocityChannelInitializer.java:57)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[01:05:05] [Netty NIO Worker #1/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 35 more
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.lang.reflect.InvocationTargetException
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.viaversion.viaversion.velocity.handlers.VelocityChannelInitializer.initChannel(VelocityChannelInitializer.java:57)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[01:05:06] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 35 more
[01:05:07] [Netty NIO Worker #2/INFO] [limboapi]: Bl_ckBuster (/127.0.0.1:50541) has connected to the LimboFilter Limbo
[01:05:07] [Netty NIO Worker #2/INFO] [limbofilter]: [connected player] Bl_ckBuster (/127.0.0.1:50541) has client brand vanilla
[01:05:08] [nioEventLoopGroup-5-1/INFO] [geyser]: Geyser runned on 0.0.0.0:19132
[01:05:08] [Velocity Async Event Executor - #2/INFO] [geyser]: Done (4,919s)! Use command /geyser help for help!
[01:05:14] [Netty NIO Worker #2/INFO] [limboapi]: Bl_ckBuster (/127.0.0.1:50541) has disconnected from the LimboFilter Limbo
[01:05:14] [Netty NIO Worker #2/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] Bl_ckBuster (/127.0.0.1:50541) has disconnected: There are no servers available to connect to. Please try again later or contact your administrator.
[01:05:15] [Thread-3/INFO] [CommandSync]: Received new connection from 127.0.0.1
[01:05:15] [Thread-3/INFO] [CommandSync]: Connection from 127.0.0.1:50650 under name Hub-1 has been authorised
```

**Comment by JNNGL** [comment]
Update FastMOTD

**Comment by JNNGL** [comment]
https://github.com/Elytrium/FastMOTD/releases/tag/dev-build
