### ISSUE TITLE
 velocity-3.3.0-SNAPSHOT-304 support

### ISSUE THREAD

**Issue by candy999** [Elytrium/FastMOTD#26]
[com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to fastmotd

```
[10:04:58] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.3.0-SNAPSHOT (git-e703e9d2-b304)...
[10:04:58] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading localizations...
[10:04:59] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Connections will use NIO channels, Java compression, Java ciphers
[10:05:01] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading plugins...
[10:05:03] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin alwaysonline 6.2.4 by Dablakbandit
[10:05:04] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin fastmotd 1.0.4-SNAPSHOT by Elytrium (https://elytrium.net/)
[10:05:04] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin geyser 2.2.0-SNAPSHOT (git-master-58ff00d) by GeyserMC
[10:05:04] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin luckperms 5.4.108 by Luck
[10:05:04] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin raknetify 0.1.0+alpha.5.109 by ishland
[10:05:05] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin send 3.0.0 by OskarsMC, OskarZyg
[10:05:05] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin vpacketevents 1.1.0 by 4drian3d
[10:05:05] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin signedvelocity 1.2.1 by 4drian3d
[10:05:05] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin velocityrcon 1.0 by UnioDex
[10:05:06] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin viaversion 4.9.3-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[10:05:06] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin viabackwards 4.9.2-SNAPSHOT by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[10:05:06] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 11 plugins
[10:05:09] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: [96m       [36m __    [0m
[10:05:09] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: [96m  |    [36m|__)   [0m[32mLuckPerms[0m [96mv5.4.108[0m
[10:05:09] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: [96m  |___ [36m|      [90mRunning on Velocity - Velocity[0m
[10:05:09] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: 
[10:05:09] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading configuration...
[10:05:14] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading storage provider... [H2]
[10:05:15] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading internal permission managers...
[10:05:15] [Velocity Async Event Executor - #0/INFO] [luckperms]: Performing initial data load...
[10:05:15] [Velocity Async Event Executor - #0/INFO] [luckperms]: Successfully enabled. (took 8711ms)
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Loading configuration...
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Successfully loaded previous state variables!
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Loading file database...
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Database is ready to go!
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Head Session server check: true
[10:05:15] [Velocity Async Event Executor - #0/INFO] [alwaysonline]: Total check methods active: 1
[10:05:15] [Velocity Async Event Executor - #0/INFO] [fastmotd]: Hooked into ServerChannelInitializer
[10:05:17] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to fastmotd
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.packet.Disconnect com.velocitypowered.proxy.protocol.packet.Disconnect.create(net.kyori.adventure.text.Component, com.velocitypowered.api.network.ProtocolVersion)'
	at net.elytrium.fastmotd.FastMOTD.lambda$reload$0(FastMOTD.java:202) ~[?:?]
	at net.elytrium.fastmotd.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:132) ~[?:?]
	at net.elytrium.fastmotd.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:118) ~[?:?]
	at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:202) ~[?:?]
	at net.elytrium.fastmotd.FastMOTD.onProxyInitialization(FastMOTD.java:142) ~[?:?]
	at net.elytrium.fastmotd.Lmbda$2.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-304.jar:3.3.0-SNAPSHOT (git-e703e9d2-b304)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-304.jar:3.3.0-SNAPSHOT (git-e703e9d2-b304)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-304.jar:3.3.0-SNAPSHOT (git-e703e9d2-b304)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[10:05:17] [Velocity Async Event Executor - #0/INFO] [geyser]: 正在載入擴展...
[10:05:17] [Velocity Async Event Executor - #0/INFO] [geyser]: 已載入 0 個擴展程序
[10:05:17] [Velocity Async Event Executor - #0/INFO] [raknetify]: Bootstrapping raknetify in wrapped environment
[10:05:18] [Velocity Async Event Executor - #0/INFO] [signedvelocity]: Starting SignedVelocity
[10:05:18] [Velocity Async Event Executor - #0/INFO] [velocityrcon]: Binding rcon to address: /0.0.0.0:25576
[10:05:18] [Via-Mappingloader-0/INFO] [viaversion]: Loading block connection mappings ...
[10:05:19] [Velocity Async Event Executor - #0/INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[10:05:19] [Velocity Async Event Executor - #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[10:05:19] [Velocity Async Event Executor - #0/WARN] [com.velocitypowered.proxy.network.ConnectionManager]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[10:05:19] [Velocity Async Event Executor - #0/INFO] [viabackwards]: Loading translations...
[10:05:20] [Velocity Async Event Executor - #0/INFO] [viabackwards]: Registering protocols...
[10:05:21] [Velocity Async Event Executor - #0/INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[10:05:21] [Velocity Async Event Executor - #0/INFO] [viaversion]: Highest supported version by the proxy: 1.20.3/1.20.4 (765)
[10:05:21] [ViaVersion - Task Executor #2/INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
[10:05:21] [Netty NIO Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0]:25565
[10:05:21] [Velocity Async Event Executor - #2/INFO] [geyser]: ******************************************
[10:05:21] [Velocity Async Event Executor - #2/INFO] [geyser]: 
[10:05:21] [Velocity Async Event Executor - #2/INFO] [geyser]: 正在載入 Geyser 版本 2.2.0-SNAPSHOT (git-master-58ff00d)
[10:05:21] [Velocity Async Event Executor - #2/INFO] [geyser]: 
[10:05:21] [Velocity Async Event Executor - #2/INFO] [geyser]: ******************************************
[10:05:21] [Netty NIO Worker #3/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening for GS4 query on /[0:0:0:0:0:0:0:0]:25566
[10:05:21] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (24.37s)!
[10:05:21] [ViaVersion - Task Executor #1/WARN] [viaversion]: You are running a development version of the plugin, please report any bugs to GitHub.
[10:05:26] [Velocity Async Event Executor - #2/INFO] [geyser]: Geyser 在 0.0.0.0:19132 啟動
[10:05:26] [Velocity Async Event Executor - #2/INFO] [geyser]: 完成 (5.151s)！ 執行 /geyser help 來取得說明！
[10:05:27] [Velocity Async Event Executor - #2/INFO] [raknetify]: Raknetify server started on /[fe80:0:0:0:b0f0:38c6:ba24:910d%59]:25565
[10:05:27] [Velocity Async Event Executor - #2/INFO] [raknetify]: Raknetify server started on /172.19.249.153:25565
[10:05:27] [Velocity Async Event Executor - #2/INFO] [raknetify]: Raknetify server started on /[0:0:0:0:0:0:0:1]:25565
[10:05:27] [Velocity Async Event Executor - #2/INFO] [raknetify]: Raknetify server started on /127.0.0.1:25565
[10:06:05] [Thread-3/INFO] [com.velocitypowered.proxy.VelocityServer]: Shutting down the proxy...
[10:06:05] [Velocity Async Event Executor - #6/INFO] [raknetify]: Closing Raknetify server /127.0.0.1:25565
[10:06:05] [Velocity Async Event Executor - #6/INFO] [raknetify]: Closing Raknetify server /172.19.249.153:25565
[10:06:05] [Velocity Async Event Executor - #6/INFO] [raknetify]: Closing Raknetify server /[0:0:0:0:0:0:0:1]:25565
[10:06:05] [Velocity Async Event Executor - #6/INFO] [raknetify]: Closing Raknetify server /[fe80:0:0:0:b0f0:38c6:ba24:910d%59]:25565
[10:06:05] [Thread-3/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Closing endpoint /0.0.0.0:25565
[10:06:05] [Thread-3/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Closing endpoint /0.0.0.0:25566
[10:06:05] [Velocity Async Event Executor - #8/INFO] [geyser]: 正在關閉 Geyser。
[10:06:05] [Velocity Async Event Executor - #8/INFO] [geyser]: Geyser 成功關閉。
[10:06:05] [Velocity Async Event Executor - #8/INFO] [velocityrcon]: Trying to stop RCON listener
[10:06:05] [Velocity Async Event Executor - #8/INFO] [luckperms]: Starting shutdown process...
[10:06:05] [Velocity Async Event Executor - #8/INFO] [luckperms]: Closing storage...
[10:06:05] [Velocity Async Event Executor - #8/INFO] [luckperms]: Goodbye!

```

**Comment by harryprogramer** [comment]
same error for me

**Comment by Deimosssss** [comment]
Yup, I have the same error.
