### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to fastmotd

### ISSUE THREAD

**Issue by candy999** [Elytrium/FastMOTD#28]
Sometimes when this kind of error occurs, motd will not be displayed correctly.

```
[23:43:27 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-08c03aae-b320)...
[23:43:28 INFO]: Loading localizations...
[23:43:28 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[23:43:28 INFO]: Loading plugins...
[23:43:28 INFO]: Loaded plugin alwaysonline 6.2.8 by Dablakbandit
[23:43:28 INFO]: Loaded plugin fastmotd 1.0.4 by Elytrium (https://elytrium.net/)
[23:43:28 INFO]: Loaded plugin geyser 2.2.0-SNAPSHOT (git-master-58ff00d) by GeyserMC
[23:43:28 INFO]: Loaded plugin luckperms 5.4.108 by Luck
[23:43:28 INFO]: Loaded plugin raknetify 0.1.0+alpha.5.109 by ishland
[23:43:28 INFO]: Loaded plugin send 3.0.0 by OskarsMC, OskarZyg
[23:43:28 INFO]: Loaded plugin vpacketevents 1.1.0 by 4drian3d
[23:43:28 INFO]: Loaded plugin signedvelocity 1.2.1 by 4drian3d
[23:43:28 INFO]: Loaded plugin velocityrcon 1.0 by UnioDex
[23:43:28 INFO]: Loaded plugin viaversion 4.9.3-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv [23:43:28 INFO]: Loaded plugin viabackwards 4.9.2-SNAPSHOT by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[23:43:28 INFO]: Loaded 11 plugins
[23:43:28 INFO]:         __
[23:43:28 INFO]:   |    |__)   LuckPerms v5.4.108
[23:43:28 INFO]:   |___ |      Running on Velocity - Velocity
[23:43:28 INFO]:
[23:43:28 INFO] [luckperms]: Loading configuration...
[23:43:29 INFO] [luckperms]: Loading storage provider... [H2]
[23:43:29 INFO] [luckperms]: Loading internal permission managers...
[23:43:29 INFO] [luckperms]: Performing initial data load...
[23:43:29 INFO] [luckperms]: Successfully enabled. (took 665ms)
[23:43:29 INFO] [alwaysonline]: Loading configuration...
[23:43:29 INFO] [alwaysonline]: Successfully loaded previous state variables!
[23:43:29 INFO] [alwaysonline]: Loading file database...
[23:43:29 INFO] [alwaysonline]: Database is ready to go!
[23:43:29 INFO] [alwaysonline]: Head Session server check: true
[23:43:29 INFO] [alwaysonline]: Total check methods active: 1
[23:43:29 INFO] [fastmotd]: Hooked into ServerChannelInitializer
[23:43:34 ERROR]: Couldn't pass ProxyInitializeEvent to fastmotd
java.io.UncheckedIOException: Unable to check for updates.
        at net.elytrium.fastmotd.thirdparty.commons.utils.updates.UpdatesChecker.checkVersionByURL(UpdatesChecker.java:47) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:147) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.onProxyInitialization(FastMOTD.java:141) ~[?:?]
        at net.elytrium.fastmotd.Lmbda$2.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.commons.utils.updates.UpdatesChecker.checkVersionByURL(UpdatesChecker.java:45) ~[?:?]
        ... 9 more
[23:43:34 INFO] [geyser]: 正在載入擴展...
[23:43:34 INFO] [geyser]: 已載入 0 個擴展程序
[23:43:34 INFO] [raknetify]: Bootstrapping raknetify in wrapped environment
[23:43:34 INFO] [signedvelocity]: Starting SignedVelocity
[23:43:34 INFO] [velocityrcon]: Binding rcon to address: /0.0.0.0:25576
[23:43:34 INFO] [viaversion]: Loading block connection mappings ...
[23:43:34 INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[23:43:34 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[23:43:34 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[23:43:34 INFO] [viabackwards]: Loading translations...
[23:43:34 INFO] [viabackwards]: Registering protocols...
[23:43:35 INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[23:43:35 INFO] [viaversion]: Highest supported version by the proxy: 1.20.3/1.20.4 (765)
[23:43:35 INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
[23:43:35 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[23:43:35 INFO] [geyser]: ******************************************
[23:43:35 INFO] [geyser]:
[23:43:35 INFO] [geyser]: 正在載入 Geyser 版本 2.2.0-SNAPSHOT (git-master-58ff00d)
[23:43:35 INFO] [geyser]:
[23:43:35 INFO] [geyser]: ******************************************
[23:43:35 INFO]: Listening for GS4 query on /[0:0:0:0:0:0:0:0]:25566
[23:43:35 INFO]: Done (7.61s)!
[23:43:36 INFO] [geyser]: Geyser 在 0.0.0.0:19132 啟動
[23:43:36 INFO] [geyser]: 完成 (1.468s)！ 執行 /geyser help 來取得說明！
[23:43:36 INFO] [raknetify]: Raknetify server started on /[fe80:0:0:0:b01c:3a9d:bbb2:a14e%48]:25565
[23:43:36 INFO] [raknetify]: Raknetify server started on /172.28.28.14:25565
[23:43:36 INFO] [raknetify]: Raknetify server started on /[0:0:0:0:0:0:0:1]:25565
[23:43:36 INFO] [raknetify]: Raknetify server started on /127.0.0.1:25565
```

**Comment by DHCPCD9** [comment]
You have bad routing to GitHub, it just can’t check updates.
