### ISSUE TITLE
 Couldn't pass ProxyInitializeEvent to fastmotd

### ISSUE THREAD

**Issue by ZiomekMinecraft** [Elytrium/FastMOTD#31]
```
[19:15:26 INFO] [fastmotd]: Hooked into ServerChannelInitializer
[19:15:26 ERROR]: Couldn't pass ProxyInitializeEvent to fastmotd
java.lang.IllegalStateException: Got unknown marker when reading map: n
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.YamlReader.readMapFromMarker(YamlReader.java:455) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.YamlReader.readMap(YamlReader.java:255) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readMap(AbstractReader.java:335) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readMapByType(AbstractReader.java:285) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readByType(AbstractReader.java:210) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readAndDeserializeByType(AbstractReader.java:176) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readNode(AbstractReader.java:135) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.YamlReader.readSerializableObject(YamlReader.java:137) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readByType(AbstractReader.java:239) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readAndDeserializeByType(AbstractReader.java:176) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readNode(AbstractReader.java:135) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.YamlReader.readSerializableObject(YamlReader.java:137) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readByType(AbstractReader.java:239) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readAndDeserializeByType(AbstractReader.java:176) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readNode(AbstractReader.java:135) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.YamlReader.readSerializableObject(YamlReader.java:137) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.reader.AbstractReader.readSerializableObject(AbstractReader.java:76) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.object.AbstractSerializable.load(AbstractSerializable.java:119) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.object.AbstractSerializable.load(AbstractSerializable.java:108) ~[?:?]
        at net.elytrium.fastmotd.thirdparty.serializer.language.object.AbstractSerializable.reload(AbstractSerializable.java:75) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:145) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.onProxyInitialization(FastMOTD.java:141) ~[?:?]
        at net.elytrium.fastmotd.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-74c932e5-b363)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-74c932e5-b363)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-74c932e5-b363)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

When I change in config this ( look on code bellow ) to null this error ( look on console log above ) show.
```yaml
  versions:
    #null = disabled
    descriptions: null
    #null = disabled
    favicons: null
    #null = disabled
    information: null
```

**Comment by SkyWatcher2019** [comment]
try to replace `null` with `{}`

**Comment by DongShaoNB** [comment]
> try to replace `null` with `{}`

some key need `[]`

**Comment by MastereQ1337** [comment]
for me {} worked, thanks
