### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by thiagogebrimm** [Elytrium/FastMOTD#9]
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command fastmotdreload for com.velocitypowered.proxy.console.VelocityConsole@6bbcba25
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command fastmotdreload for com.velocitypowered.proxy.console.VelocityConsole@6bbcba25
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.elytrium.fastmotd.holder.MOTDHolder.dispose()" because "holder" is null
        at net.elytrium.fastmotd.utils.MOTDGenerator.dispose(MOTDGenerator.java:144) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:117) ~[?:?]
        at net.elytrium.fastmotd.command.ReloadCommand.execute(ReloadCommand.java:35) ~[?:?]
        at net.elytrium.fastmotd.command.ReloadCommand.execute(ReloadCommand.java:24) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-1a3fba42-b163)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```

**Comment by JNNGL** [comment]
Use dev build

**Comment by thiagogebrimm** [comment]
thanks
